name: Build release
on:
  push:
    branches:
      - "*"

env:
  ZLIB_MUSL_VERSION: 1.2.12
  ZLIB_MUSL_CHECKSUM: 28687d676c04e7103bb6ff2b9694c471

  LIBCAP_MUSL_VERSION: 2.33
  LIBCAP_MUSL_CHECKSUM: c23bbc02b13d10c3889ef2b1bed34071

  JSONC_MUSL_VERSION: 0.13.1-20180305
  JSONC_MUSL_CHECKSUM: 20dba7bf773599a0842745a2fe5b7cd3

  OPENSSL_MUSL_VERSION: 1.1.1d
  OPENSSL_MUSL_CHECKSUM: 3be209000dbc7e1b95bcdf47980a3baa

  LIBWEBSOCKETS_MUSL_VERSION: 3.2.0
  LIBWEBSOCKETS_MUSL_CHECKSUM: 1d06f5602604e67e6f50cef9857c6b0c

  MAKEOPTS: -j 12


#on:
#  release:
#    types: [created]
jobs:
  static:
    name: Create release artifact (static)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential musl musl-tools curl wget cmake xxd

      - name: Download static dependencies
        run: |
          mkdir staging
          cd staging

          wget https://www.zlib.net/zlib-${ZLIB_MUSL_VERSION}.tar.xz
          wget https://git.kernel.org/pub/scm/linux/kernel/git/morgan/libcap.git/snapshot/libcap-${LIBCAP_MUSL_VERSION}.tar.gz
          wget https://github.com/json-c/json-c/archive/json-c-${JSONC_MUSL_VERSION}.tar.gz
          wget https://www.openssl.org/source/openssl-${OPENSSL_MUSL_VERSION}.tar.gz
          wget https://github.com/warmcat/libwebsockets/archive/v${LIBWEBSOCKETS_MUSL_VERSION}.tar.gz -O libwebsockets-${LIBWEBSOCKETS_MUSL_VERSION}.tar.gz

      - name: Verify download checksums
        run: |
          cd staging
          echo "$ZLIB_MUSL_CHECKSUM  zlib-${ZLIB_MUSL_VERSION}.tar.xz" > checksums
          echo "$LIBCAP_MUSL_CHECKSUM  libcap-${LIBCAP_MUSL_VERSION}.tar.gz" >> checksums
          echo "$JSONC_MUSL_CHECKSUM  json-c-${JSONC_MUSL_VERSION}.tar.gz" >> checksums
          echo "$OPENSSL_MUSL_CHECKSUM  openssl-${OPENSSL_MUSL_VERSION}.tar.gz" >> checksums
          echo "$LIBWEBSOCKETS_MUSL_CHECKSUM  libwebsockets-${LIBWEBSOCKETS_MUSL_VERSION}.tar.gz" >> checksums

          md5sum -c checksums
 
      - name: Extract static dependencies sources
        run: |
          cd staging
          tar -xf zlib-${ZLIB_MUSL_VERSION}.tar.xz
          tar -xf openssl-${OPENSSL_MUSL_VERSION}.tar.gz
          tar -xf libwebsockets-${LIBWEBSOCKETS_MUSL_VERSION}.tar.gz
          tar -xf libcap-${LIBCAP_MUSL_VERSION}.tar.gz
          tar -xf json-c-${JSONC_MUSL_VERSION}.tar.gz

      - name: Prepare system for musl-build
        run: |
          ln -fs /usr/include/linux /usr/include/x86_64-linux-musl/
          ln -fs /usr/include/asm-generic /usr/include/x86_64-linux-musl/
          ln -fs /usr/include/x86_64-linux-gnu/asm /usr/include/x86_64-linux-musl/
          ln -fs /usr/include/x86_64-linux-gnu/sys/queue.h /usr/include/x86_64-linux-musl/sys/      

      - name: Build: zlib (musl)
        run: |
          cd staging/zlib-${ZLIB_MUSL_VERSION}

          CC="musl-gcc" CFLAGS="-fPIC" ./configure --prefix /
          make ${MAKEOPTS}
          make DESTDIR="${ROOTDIR}" install

          echo $ROOTDIR
          ls $ROOTDIR

      - name: Build: libpcap (musl)
        run: |
          cd staging/libcap-${LIBCAP_MUSL_VERSION}

      - name: Build: libjsonc (musl)
        run: |
          cd staging/json-c-json-c-${JSONC_MUSL_VERSION}

      - name: Build: openssl (musl)
        run: |
          cd staging/openssl-${OPENSSL_MUSL_VERSION}
          
      - name: Build: libwebsockets (musl)
        run: |
          cd staging/libwebsockets-${LIBWEBSOCKETS_MUSL_VERSION}

      - name: Build: corex (static, musl)
        run: |
          cd src

          make

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'corex-*-linux-static'

